name: Deploy Docs

on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build docs
        run: |
          cd docs/
          sphinx-build -b html -a -E -d _build/doctrees . _build/html

      - name: Create version file
        run: |
          echo "{\"version\": \"${GITHUB_REF#refs/tags/}\"}" > docs/_build/html/version.json

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html/
